import { useEffect, useState, useMemo } from 'react'
import { useNavigate } from 'react-router-dom'
import { useApp } from '../contexts/AppContext'
import { useToast } from '../contexts/ToastContext'
import {
  onLezioniSettimana,
  getLezioniRange,
  onAssegnazioni,
  onOrari,
  onPercorsi,
  onUnita,
  onVacanze,
  onRicorrenze,
  onDistribuzioni,
  addLezione,
  updateLezione,
  deleteLezione,
  setDistribuzioniClasse,
} from '../lib/firestore'
import { getWeekRange } from '../lib/settimane'
import {
  costruisciLezioniDaOrario,
  chiaveLezione,
  oreDisponibiliPerAssegnazione,
  inizioEffettivo,
} from '../lib/calendario'
import {
  STATO_LEZIONE,
  GIORNI_LABEL,
  GIORNI_SHORT,
} from '../lib/costanti'
import { format, addDays, parseISO, isBefore } from 'date-fns'
import { it } from 'date-fns/locale'
import { Timestamp } from 'firebase/firestore'
import LoadingSpinner from '../components/common/LoadingSpinner'
import SlidePanel from '../components/common/SlidePanel'
import UnitaPanel from '../components/percorsi/UnitaPanel'
import WeekNavigation from '../components/settimana/WeekNavigation'
import LessonGrid from '../components/settimana/LessonGrid'
import LessonList from '../components/settimana/LessonList'
import GenerateButton from '../components/settimana/GenerateButton'
import ExtraLessonForm from '../components/settimana/ExtraLessonForm'

export default function SettimanaPage() {
  const { annoAttivo, annoConfig, annoChiuso, loading: configLoading } = useApp()
  const toast = useToast()
  const navigate = useNavigate()

  // -- Shared state --
  const [lezioni, setLezioni] = useState([])
  const [updatingLezioni, setUpdatingLezioni] = useState(new Set())
  const [assegnazioni, setAssegnazioni] = useState([])
  const [orari, setOrari] = useState([])
  const [percorsi, setPercorsi] = useState([])
  const [unitaMap, setUnitaMap] = useState({})
  const [vacanze, setVacanze] = useState([])
  const [ricorrenze, setRicorrenze] = useState({})
  const [distribuzioni, setDistribuzioni] = useState({})
  const [weekOffset, setWeekOffset] = useState(0)
  const [loading, setLoading] = useState(true)
  const [viewMode, setViewMode] = useState('grid') // 'grid' | 'list'

  // -- List-mode state --
  const [generating, setGenerating] = useState(false)
  const [editingLezione, setEditingLezione] = useState(null)
  const [showExtraForm, setShowExtraForm] = useState(false)
  const [autoGenerated, setAutoGenerated] = useState(new Set())
  const [slidePanelPercorso, setSlidePanelPercorso] = useState(null)

  const { start, end } = getWeekRange(weekOffset)

  // -- Config --
  const oreLezione = useMemo(() => annoConfig?.oreLezione || [], [annoConfig])
  const giornoLibero = annoConfig?.giornoLibero ?? null
  const dataInizioScuola = annoConfig?.dataInizioScuola || null
  const dataFineScuola = annoConfig?.dataFineScuola || null
  const hasOreConfig = oreLezione.length > 0

  // -- Data loading --
  useEffect(() => {
    if (!annoAttivo) {
      setLoading(false)
      return
    }

    setLoading(true)
    const unsubs = []

    unsubs.push(
      onLezioniSettimana(annoAttivo, start, end, (data) => {
        setLezioni(data)
        setLoading(false)
      })
    )
    unsubs.push(
      onAssegnazioni(annoAttivo, (data) => {
        setAssegnazioni(data.filter((a) => a.attiva && !a.archiviata))
      })
    )
    unsubs.push(onOrari(annoAttivo, setOrari))
    unsubs.push(onVacanze(annoAttivo, setVacanze))
    unsubs.push(onPercorsi(annoAttivo, setPercorsi))
    unsubs.push(onRicorrenze(annoAttivo, setRicorrenze))
    unsubs.push(onDistribuzioni(annoAttivo, setDistribuzioni))

    return () => unsubs.forEach((u) => u())
  }, [annoAttivo, weekOffset])

  // -- Load unita for referenced percorsi --
  // Chiave derivata stabile: risottoscrive solo quando cambia l'insieme dei percorsi
  const percorsoIdsKey = useMemo(
    () => [...new Set(lezioni.filter((l) => l.percorsoId).map((l) => l.percorsoId))].sort().join(','),
    [lezioni]
  )
  useEffect(() => {
    if (!percorsoIdsKey) return
    const unsubs = percorsoIdsKey.split(',').map((pId) =>
      onUnita(pId, (units) => {
        setUnitaMap((prev) => {
          const next = { ...prev }
          for (const u of units) next[u.id] = u
          return next
        })
      })
    )
    return () => unsubs.forEach((u) => u())
  }, [percorsoIdsKey])

  // -- Handlers --

  async function handleStatoChange(lezioneId, nuovoStato) {
    const prevStato = lezioni.find((l) => l.id === lezioneId)?.stato
    setUpdatingLezioni((prev) => new Set(prev).add(lezioneId))
    try {
      await updateLezione(lezioneId, { stato: nuovoStato })
      if (prevStato && prevStato !== nuovoStato) {
        const lez = lezioni.find((l) => l.id === lezioneId)
        if (nuovoStato === STATO_LEZIONE.SALTATA && lez) {
          toast.action(`Lezione ${lez.classe} saltata. Controlla la programmazione.`, {
            label: 'Annulla',
            onClick: () => updateLezione(lezioneId, { stato: prevStato }),
          })
        } else {
          toast.action('Stato aggiornato', {
            label: 'Annulla',
            onClick: () => updateLezione(lezioneId, { stato: prevStato }),
          })
        }
      }
    } catch {
      toast.error("Errore nell'aggiornamento dello stato della lezione")
    } finally {
      setUpdatingLezioni((prev) => { const s = new Set(prev); s.delete(lezioneId); return s })
    }
  }

  // Chiavi di dedup delle lezioni in stato (settimana visualizzata)
  function chiaviLezioni(list) {
    return new Set(
      list.map((l) => {
        const d = l.data instanceof Date ? l.data : l.data?.toDate ? l.data.toDate() : new Date(l.data)
        return chiaveLezione(format(d, 'yyyy-MM-dd'), l.oraInizio, l.classe)
      })
    )
  }

  async function salvaLezioni(nuove) {
    return Promise.all(nuove.map((l) => addLezione({ ...l, data: Timestamp.fromDate(l.data) })))
  }

  function labelGiorniSaltati(n) {
    return `${n} giorn${n === 1 ? 'o' : 'i'} non scolastic${n === 1 ? 'o' : 'i'}`
  }

  async function handleRegenerate() {
    if (!annoAttivo || orari.length === 0) return
    setGenerating(true)

    // Delete all non-extra lessons for this week
    const toDelete = lezioni.filter((l) => !l.extra)
    try {
      await Promise.all(toDelete.map((l) => deleteLezione(l.id)))
    } catch {
      toast.error('Errore durante la cancellazione delle lezioni.')
      setGenerating(false)
      return
    }

    // Le lezioni extra sopravvivono: le loro chiavi bloccano la rigenerazione dello slot
    const { lezioni: nuove, giorniSaltati } = costruisciLezioniDaOrario({
      da: inizioEffettivo(start, dataInizioScuola),
      a: addDays(start, 5),
      annoScolastico: annoAttivo,
      orari,
      vacanze,
      giornoLibero,
      ricorrenze,
      distribuzioni,
      existingKeys: chiaviLezioni(lezioni.filter((l) => l.extra)),
    })

    try {
      await salvaLezioni(nuove)
      const parts = [`${toDelete.length} lezioni eliminate, ${nuove.length} rigenerate dalla timeline`]
      if (giorniSaltati > 0) parts.push(labelGiorniSaltati(giorniSaltati))
      toast.success(parts.join(' — '))
    } catch {
      toast.error('Errore durante la rigenerazione delle lezioni.')
    }
    setGenerating(false)
  }

  async function handleGenerate() {
    if (!annoAttivo || orari.length === 0) return
    setGenerating(true)

    const { lezioni: nuove, giorniSaltati } = costruisciLezioniDaOrario({
      da: inizioEffettivo(start, dataInizioScuola),
      a: addDays(start, 5),
      annoScolastico: annoAttivo,
      orari,
      vacanze,
      giornoLibero,
      ricorrenze,
      distribuzioni,
      existingKeys: chiaviLezioni(lezioni),
    })

    try {
      await salvaLezioni(nuove)
      if (nuove.length > 0) {
        const parts = [`${nuove.length} lezioni generate`]
        if (giorniSaltati > 0) parts.push(labelGiorniSaltati(giorniSaltati))
        toast.success(parts.join(' — '))
      } else if (giorniSaltati > 0) {
        toast.info(`Nessuna lezione generata — ${labelGiorniSaltati(giorniSaltati)}`)
      }
    } catch {
      toast.error('Errore durante la generazione delle lezioni.')
    }
    setGenerating(false)
  }

  async function handleGenerateMultiWeek(numWeeks) {
    if (!annoAttivo || orari.length === 0) return
    setGenerating(true)

    const fineScuola = dataFineScuola ? parseISO(dataFineScuola) : null
    const totalWeeks = numWeeks === 'end' ? 52 : numWeeks
    const rangeStart = inizioEffettivo(start, dataInizioScuola)
    let rangeEnd = addDays(start, totalWeeks * 7 - 1)
    if (fineScuola && isBefore(fineScuola, rangeEnd)) rangeEnd = fineScuola

    try {
      // Dedup contro il DB sull'intero intervallo: lo stato locale contiene
      // solo la settimana visualizzata, non le settimane successive
      const esistenti = await getLezioniRange(annoAttivo, rangeStart, rangeEnd)

      const { lezioni: nuove, giorniSaltati } = costruisciLezioniDaOrario({
        da: rangeStart,
        a: rangeEnd,
        annoScolastico: annoAttivo,
        orari,
        vacanze,
        giornoLibero,
        ricorrenze,
        distribuzioni,
        existingKeys: chiaviLezioni(esistenti),
      })

      await salvaLezioni(nuove)

      if (nuove.length > 0) {
        const label = numWeeks === 'end' ? 'fino a fine scuola' : `${numWeeks} settimane`
        const parts = [`${nuove.length} lezioni generate (${label})`]
        if (giorniSaltati > 0) parts.push(labelGiorniSaltati(giorniSaltati))
        toast.success(parts.join(' — '))
      } else {
        toast.info('Nessuna nuova lezione da generare.')
      }
    } catch {
      toast.error('Errore durante la generazione delle lezioni.')
    }
    setGenerating(false)
  }

  async function handleSaveEdit() {
    if (!editingLezione) return
    const { id, note, titoloOverride, stato, percorsoId, unitaId } = editingLezione
    try {
      await updateLezione(id, {
        note,
        titoloOverride,
        stato,
        percorsoId: percorsoId || null,
        unitaId: unitaId || null,
      })
      setEditingLezione(null)
    } catch {
      toast.error('Errore durante il salvataggio della lezione.')
    }
  }

  // Quick save individual fields (for grid edit panel)
  async function handleQuickSave(lezioneId, updates) {
    try {
      await updateLezione(lezioneId, updates)
    } catch {
      toast.error('Errore durante il salvataggio.')
    }
  }

  async function handleSwapLezioni(lezA, lezB) {
    // Swap curriculum fields between two lessons of the same class+materia
    // (le distribuzioni sono per classe+materia: uno scambio tra materie
    // diverse mescolerebbe i curricula)
    if (!lezA || !lezB || lezA.id === lezB.id) return
    if (lezA.classe !== lezB.classe || lezA.materia !== lezB.materia) {
      toast.error('Puoi scambiare solo lezioni della stessa classe e materia')
      return
    }

    const fieldsA = { percorsoId: lezA.percorsoId || null, unitaId: lezA.unitaId || null, titoloOverride: lezA.titoloOverride || '' }
    const fieldsB = { percorsoId: lezB.percorsoId || null, unitaId: lezB.unitaId || null, titoloOverride: lezB.titoloOverride || '' }

    try {
      // Swap lesson fields in Firestore
      await Promise.all([
        updateLezione(lezA.id, fieldsB),
        updateLezione(lezB.id, fieldsA),
      ])

      // Update distribuzioni for both slots
      const classe = lezA.classe
      const materia = lezA.materia
      const classeDist = { ...(distribuzioni[classe]?.[materia] || {}) }

      function dateStr(lez) {
        const d = lez.data instanceof Date ? lez.data : lez.data?.toDate ? lez.data.toDate() : new Date(lez.data)
        return format(d, 'yyyy-MM-dd')
      }

      const keyA = `${dateStr(lezA)}_${lezA.numeroOra || 0}`
      const keyB = `${dateStr(lezB)}_${lezB.numeroOra || 0}`

      const distA = classeDist[keyA]
      const distB = classeDist[keyB]

      // Swap or set/delete distribuzioni entries
      if (fieldsA.percorsoId) {
        const percorso = percorsoMap[fieldsA.percorsoId]
        const unita = fieldsA.unitaId ? unitaMap[fieldsA.unitaId] : null
        classeDist[keyB] = {
          percorsoId: fieldsA.percorsoId,
          percorsoTitolo: percorso?.titolo || '',
          ...(fieldsA.unitaId ? { unitaId: fieldsA.unitaId, unitaTitolo: unita?.titolo || '' } : {}),
        }
      } else {
        delete classeDist[keyB]
      }

      if (fieldsB.percorsoId) {
        const percorso = percorsoMap[fieldsB.percorsoId]
        const unita = fieldsB.unitaId ? unitaMap[fieldsB.unitaId] : null
        classeDist[keyA] = {
          percorsoId: fieldsB.percorsoId,
          percorsoTitolo: percorso?.titolo || '',
          ...(fieldsB.unitaId ? { unitaId: fieldsB.unitaId, unitaTitolo: unita?.titolo || '' } : {}),
        }
      } else {
        delete classeDist[keyA]
      }

      await setDistribuzioniClasse(annoAttivo, classe, materia, classeDist)

      toast.action(`Lezioni ${lezA.classe} scambiate`, {
        label: 'Annulla',
        onClick: async () => {
          await Promise.all([
            updateLezione(lezA.id, fieldsA),
            updateLezione(lezB.id, fieldsB),
          ])
          // Restore distribuzioni
          const restoreDist = { ...(distribuzioni[classe]?.[materia] || {}) }
          if (distA) restoreDist[keyA] = distA; else delete restoreDist[keyA]
          if (distB) restoreDist[keyB] = distB; else delete restoreDist[keyB]
          await setDistribuzioniClasse(annoAttivo, classe, materia, restoreDist)
        },
      })
    } catch {
      toast.error('Errore durante lo scambio delle lezioni.')
    }
  }

  async function handleDeleteLezione(id) {
    const lez = lezioni.find((l) => l.id === id)
    if (!lez) return
    // Firestore rifiuta i campi undefined: il doc va ricreato senza id
    const { id: _id, ...datiLezione } = lez
    try {
      await deleteLezione(id)
      if (editingLezione?.id === id) setEditingLezione(null)
      toast.action('Lezione eliminata', {
        label: 'Annulla',
        onClick: () => addLezione(datiLezione),
      })
    } catch {
      toast.error("Errore durante l'eliminazione della lezione.")
    }
  }

  async function handleMarkDaySvolte(dayLezioni) {
    const pianificate = dayLezioni.filter((l) => l.stato === STATO_LEZIONE.PIANIFICATA)
    if (pianificate.length === 0) return
    try {
      await Promise.all(pianificate.map((l) => updateLezione(l.id, { stato: STATO_LEZIONE.SVOLTA })))
      toast.action(`${pianificate.length} lezioni segnate come svolte`, {
        label: 'Annulla',
        onClick: () => Promise.all(pianificate.map((l) => updateLezione(l.id, { stato: STATO_LEZIONE.PIANIFICATA }))),
      })
    } catch {
      toast.error("Errore durante l'aggiornamento.")
    }
  }

  // Auto-generate in list mode
  useEffect(() => {
    if (viewMode !== 'list' || loading || !annoAttivo || annoChiuso || generating) return
    if (lezioni.length > 0 || orari.length === 0) return
    const weekKey = format(start, 'yyyy-MM-dd')
    if (autoGenerated.has(weekKey)) return
    setAutoGenerated((prev) => new Set(prev).add(weekKey))
    handleGenerate()
  }, [viewMode, loading, annoAttivo, annoChiuso, lezioni.length, orari.length, start, generating])

  // -- Derived data --

  // Days structure for grid view
  const days = useMemo(() => {
    const result = []
    for (let i = 0; i < 6; i++) {
      const date = addDays(start, i)
      const dayStr = format(date, 'yyyy-MM-dd')
      const vacanza = vacanze.find((v) => dayStr >= v.dataInizio && dayStr <= v.dataFine) || null
      result.push({
        index: i,
        date,
        label: GIORNI_LABEL[i],
        short: GIORNI_SHORT[i],
        isFree: i === giornoLibero,
        vacanza,
      })
    }
    return result
  }, [start, vacanze, giornoLibero])

  // Lesson grid for grid view
  const lessonGrid = useMemo(() => {
    function getNumeroOra(lez) {
      if (lez.numeroOra) return lez.numeroOra
      const match = oreLezione.find((o) => o.inizio === lez.oraInizio)
      return match ? match.numero : null
    }

    const grid = {}
    for (const lez of lezioni) {
      const data = lez.data instanceof Date ? lez.data : lez.data?.toDate ? lez.data.toDate() : new Date(lez.data)
      const dayStr = format(data, 'yyyy-MM-dd')
      for (let i = 0; i < 6; i++) {
        if (format(addDays(start, i), 'yyyy-MM-dd') === dayStr) {
          const numOra = getNumeroOra(lez)
          if (numOra) grid[`${i}_${numOra}`] = lez
          break
        }
      }
    }
    return grid
  }, [start, lezioni, oreLezione])

  // Days structure for list view (with lessons per day + expected slots)
  const giorniSettimana = useMemo(() => {
    const result = []
    for (let i = 0; i < 6; i++) {
      const date = addDays(start, i)
      const dayStr = format(date, 'yyyy-MM-dd')

      const dayLezioni = lezioni
        .filter((lez) => {
          const d = lez.data instanceof Date ? lez.data : lez.data?.toDate ? lez.data.toDate() : new Date(lez.data)
          return format(d, 'yyyy-MM-dd') === dayStr
        })
        .sort((a, b) => (a.oraInizio || '').localeCompare(b.oraInizio || ''))

      const expectedSlots = orari
        .filter((o) => o.giorno === i)
        .sort((a, b) => a.oraInizio.localeCompare(b.oraInizio))

      const vacanza = vacanze.find((v) => dayStr >= v.dataInizio && dayStr <= v.dataFine) || null

      result.push({ index: i, date, dayStr, label: GIORNI_LABEL[i], lezioni: dayLezioni, expectedSlots, vacanza })
    }
    return result
  }, [start, lezioni, orari, vacanze])

  // Percorso lookup
  const percorsoMap = useMemo(() => {
    const map = {}
    for (const p of percorsi) map[p.id] = p
    return map
  }, [percorsi])

  // Remaining hours calculation — da oggi (i giorni già trascorsi non contano)
  const oreRimanentiPerClasse = useMemo(() => {
    if (!dataFineScuola || orari.length === 0) return null
    const fineScuola = parseISO(dataFineScuola)
    const oggi = new Date()
    if (fineScuola <= oggi) return null

    const orePerClasse = oreDisponibiliPerAssegnazione(orari, {
      da: inizioEffettivo(oggi, dataInizioScuola),
      a: fineScuola,
      giornoLibero,
      vacanze,
    })

    return Object.entries(orePerClasse).map(([key, totaleOre]) => {
      const [classe, materia] = key.split('|')
      const oreSettimana = orari
        .filter((o) => o.classe === classe && o.giorno !== giornoLibero)
        .reduce((s, o) => s + (o.ore || 1), 0)
      return { classe, materia, oreSettimana, totaleOre }
    }).sort((a, b) => a.classe.localeCompare(b.classe))
  }, [dataInizioScuola, dataFineScuola, orari, vacanze, giornoLibero])

  // -- Render --

  if (configLoading || loading) return <LoadingSpinner />

  if (!annoAttivo) {
    return (
      <div className="text-center py-12">
        <h2 className="text-xl font-semibold text-fg mb-2">Settimana</h2>
        <p className="text-fg-muted">
          Configura l'anno scolastico nelle Impostazioni per iniziare.
        </p>
      </div>
    )
  }

  const weekLabel = `${format(start, 'd MMM', { locale: it })} – ${format(end, 'd MMM yyyy', { locale: it })}`
  const hasOrari = orari.length > 0

  return (
    <div className="max-w-6xl mx-auto">
      {/* Header: title + view toggle + week nav */}
      <div className="flex flex-wrap items-center justify-between gap-3 mb-6">
        <div className="flex items-center gap-4">
          <h1 className="text-2xl font-bold text-fg">Settimana</h1>
          {/* View toggle */}
          <div className="flex bg-overlay rounded-sm p-0.5 border border-edge-muted">
            <button
              onClick={() => setViewMode('grid')}
              className={`px-3 py-1.5 text-sm font-medium rounded-sm transition-colors ${
                viewMode === 'grid'
                  ? 'bg-surface text-fg'
                  : 'text-fg-muted hover:text-fg'
              }`}
            >
              <span className="flex items-center gap-1.5">
                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 6A2.25 2.25 0 016 3.75h2.25A2.25 2.25 0 0110.5 6v2.25a2.25 2.25 0 01-2.25 2.25H6a2.25 2.25 0 01-2.25-2.25V6zm0 9.75A2.25 2.25 0 016 13.5h2.25a2.25 2.25 0 012.25 2.25V18a2.25 2.25 0 01-2.25 2.25H6A2.25 2.25 0 013.75 18v-2.25zM13.5 6a2.25 2.25 0 012.25-2.25H18A2.25 2.25 0 0120.25 6v2.25A2.25 2.25 0 0118 10.5h-2.25a2.25 2.25 0 01-2.25-2.25V6zm0 9.75a2.25 2.25 0 012.25-2.25H18a2.25 2.25 0 012.25 2.25V18A2.25 2.25 0 0118 20.25h-2.25a2.25 2.25 0 01-2.25-2.25v-2.25z" />
                </svg>
                Griglia
              </span>
            </button>
            <button
              onClick={() => setViewMode('list')}
              className={`px-3 py-1.5 text-sm font-medium rounded-sm transition-colors ${
                viewMode === 'list'
                  ? 'bg-surface text-fg'
                  : 'text-fg-muted hover:text-fg'
              }`}
            >
              <span className="flex items-center gap-1.5">
                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M8.25 6.75h12M8.25 12h12m-12 5.25h12M3.75 6.75h.007v.008H3.75V6.75zm.375 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zM3.75 12h.007v.008H3.75V12zm.375 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm-.375 5.25h.007v.008H3.75v-.008zm.375 0a.375.375 0 11-.75 0 .375.375 0 01.75 0z" />
                </svg>
                Lista
              </span>
            </button>
          </div>
        </div>
        <WeekNavigation weekOffset={weekOffset} setWeekOffset={setWeekOffset} weekLabel={weekLabel} />
      </div>

      {/* Generate + Extra buttons (list mode, or grid mode with orari) */}
      {viewMode === 'list' && !annoChiuso && (
        <>
          <GenerateButton
            onGenerate={handleGenerate}
            onGenerateMultiWeek={handleGenerateMultiWeek}
            onRegenerate={handleRegenerate}
            generating={generating}
            hasOrari={hasOrari}
            lezioniCount={lezioni.length}
            onToggleExtra={() => setShowExtraForm((v) => !v)}
            showExtraForm={showExtraForm}
            hasDataFineScuola={!!dataFineScuola}
          />

          {showExtraForm && (
            <ExtraLessonForm
              annoAttivo={annoAttivo}
              assegnazioni={assegnazioni}
              onClose={() => setShowExtraForm(false)}
              onSuccess={() => toast.success('Lezione extra aggiunta')}
            />
          )}

          {!hasOrari && (
            <div className="mb-6 p-4 bg-badge-warn border border-warn/30 rounded-sm">
              <p className="text-sm text-warn">
                Definisci prima il tuo orario settimanale nelle <strong>Impostazioni</strong> per poter generare le lezioni automaticamente.
              </p>
            </div>
          )}
        </>
      )}

      {/* -- Grid view -- */}
      {viewMode === 'grid' && (
        <>
          {/* Generate / Regenerate button for grid mode */}
          {hasOreConfig && hasOrari && !annoChiuso && lezioni.length === 0 && (
            <div className="mb-4 px-4 py-3 bg-badge-p border border-link/30 rounded-sm flex items-center justify-between gap-3">
              <p className="text-sm text-link">
                {generating ? 'Generazione lezioni in corso...' : 'Settimana senza lezioni.'}
              </p>
              {!generating && (
                <button
                  onClick={handleGenerate}
                  className="px-4 py-1.5 bg-link text-white text-sm font-medium rounded-sm hover:bg-link/80 shrink-0"
                >
                  Genera da orario
                </button>
              )}
            </div>
          )}
          {hasOreConfig && hasOrari && !annoChiuso && lezioni.length > 0 && (
            <div className="mb-4 flex justify-end">
              <button
                onClick={handleRegenerate}
                disabled={generating}
                className="px-4 py-1.5 bg-warn text-canvas text-sm font-medium rounded-sm hover:bg-warn/80 disabled:opacity-50"
              >
                {generating ? 'Rigenerazione...' : 'Rigenera'}
              </button>
            </div>
          )}

          {hasOreConfig ? (
            <LessonGrid
              days={days}
              oreLezione={oreLezione}
              lessonGrid={lessonGrid}
              percorsoMap={percorsoMap}
              unitaMap={unitaMap}
              updatingLezioni={updatingLezioni}
              onStatoChange={handleStatoChange}
              onQuickSave={handleQuickSave}
              onDeleteLezione={handleDeleteLezione}
              percorsi={percorsi}
              giornoLibero={giornoLibero}
              onOpenPercorso={(p) => setSlidePanelPercorso(p)}
              onSwapLezioni={handleSwapLezioni}
            />
          ) : (
            <div className="mb-6 p-4 bg-badge-warn border border-warn/30 rounded-sm">
              <p className="text-sm text-warn">
                Configura le <strong>ore scolastiche</strong> nelle Impostazioni per vedere la griglia settimanale.
                In alternativa, usa la vista <button onClick={() => setViewMode('list')} className="underline font-semibold">Lista</button>.
              </p>
            </div>
          )}

          {/* Ore rimanenti */}
          {oreRimanentiPerClasse && oreRimanentiPerClasse.length > 0 && (
            <div className="mb-6">
              <h2 className="text-lg font-semibold text-fg mb-3">
                Ore rimanenti fino al {format(parseISO(dataFineScuola), 'd MMMM yyyy', { locale: it })}
              </h2>
              <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">
                {oreRimanentiPerClasse.map(({ classe, materia, oreSettimana, totaleOre }) => (
                  <div
                    key={`${classe}_${materia}`}
                    onClick={() => navigate('/programmazione')}
                    className="flex items-center justify-between p-3 bg-surface rounded-sm border border-edge cursor-pointer hover:border-link/40 transition-colors"
                  >
                    <div>
                      <span className="text-sm font-bold text-fg">{classe}</span>
                      <span className="text-sm text-fg-muted ml-1.5">{materia}</span>
                    </div>
                    <div className="text-right">
                      <span className="text-lg font-bold text-link font-mono">{totaleOre}</span>
                      <span className="text-xs text-fg-subtle ml-0.5">h</span>
                      <div className="text-[10px] text-fg-subtle leading-tight font-mono">
                        {oreSettimana}h/sett (vacanze escluse)
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Hint if no dataFineScuola */}
          {!dataFineScuola && orari.length > 0 && (
            <div className="mb-6 p-3 bg-badge-warn border border-warn/30 rounded-sm">
              <p className="text-xs text-warn">
                Imposta l'<strong>ultimo giorno di scuola</strong> nelle Impostazioni per vedere il calcolo delle ore rimanenti per ogni classe.
              </p>
            </div>
          )}

          {/* Active assignments progress */}
          {assegnazioni.length > 0 && (
            <div>
              <h2 className="text-lg font-semibold text-fg mb-4">Percorsi attivi</h2>
              <div className="grid gap-3 sm:grid-cols-2">
                {assegnazioni.map((a) => {
                  const progresso = a.progresso || {}
                  const totale = Object.keys(progresso).length
                  const completate = Object.values(progresso).filter((p) => p.stato === 'completata').length
                  const pct = totale > 0 ? Math.round((completate / totale) * 100) : 0

                  return (
                    <div
                      key={a.id}
                      onClick={() => navigate('/percorsi')}
                      className="p-4 bg-surface rounded-sm border border-edge cursor-pointer hover:border-link/40 transition-colors"
                    >
                      <div className="flex items-center justify-between mb-2">
                        <span className="text-sm font-medium text-fg">
                          {a.classe} — {a.materia}
                        </span>
                        <span className="text-xs text-fg-muted font-mono">{pct}%</span>
                      </div>
                      <div className="w-full bg-edge-muted rounded-full h-2">
                        <div
                          className="bg-link h-2 rounded-full transition-all"
                          style={{ width: `${pct}%` }}
                        />
                      </div>
                    </div>
                  )
                })}
              </div>
            </div>
          )}
        </>
      )}

      {/* -- List view -- */}
      {viewMode === 'list' && (
        <LessonList
          giorniSettimana={giorniSettimana}
          percorsi={percorsi}
          updatingLezioni={updatingLezioni}
          editingLezione={editingLezione}
          setEditingLezione={setEditingLezione}
          onStatoChange={handleStatoChange}
          onSaveEdit={handleSaveEdit}
          onDeleteLezione={handleDeleteLezione}
          onMarkDaySvolte={handleMarkDaySvolte}
        />
      )}

      {/* ── SlidePanel for editing percorso ── */}
      <SlidePanel
        open={slidePanelPercorso !== null}
        onClose={() => setSlidePanelPercorso(null)}
        title={slidePanelPercorso ? `${slidePanelPercorso.titolo} — ${slidePanelPercorso.classe}` : ''}
        width="md"
      >
        {slidePanelPercorso && (
          <UnitaPanel percorso={slidePanelPercorso} />
        )}
      </SlidePanel>
    </div>
  )
}
